[platformio]
default_envs = baud115200

[env]
platform = ststm32
board = nucleo_f446re
framework = cmsis
upload_protocol = stlink
build_flags = -DSTM32F446xx

[env:baud115200]
build_flags = ${env.build_flags} -DBAUD_RATE=115200

[env:baud460800]
build_flags = ${env.build_flags} -DBAUD_RATE=460800

[env:baud1000000]
build_flags = ${env.build_flags} -DBAUD_RATE=1000000